// Generated by server/pages.js — the version and file lists are filled in at
// startup from the files on disk, so every deploy gets a fresh cache.
const VERSION = '{{version}}';
const CACHE = `move-${VERSION}`;
const PRECACHE = {{precache}};
// Data files may not exist yet (e.g. first build still running), so they are
// cached best-effort instead of failing the whole install
const PRECACHE_DATA = {{precacheData}};
// Pages that must open instantly even with a bad connection (e.g. underground)
const OFFLINE_PAGES = {{offlinePages}};

self.addEventListener('install', e => {
    e.waitUntil(caches.open(CACHE).then(cache => Promise.all([
        cache.addAll(PRECACHE),
        ...PRECACHE_DATA.map(url => cache.add(url).catch(() => {})),
    ])));
    self.skipWaiting();
});

self.addEventListener('activate', e => {
    e.waitUntil(
        caches.keys().then(keys =>
            Promise.all(keys.filter(k => k !== CACHE).map(k => caches.delete(k)))
        )
    );
    self.clients.claim();
});

self.addEventListener('fetch', e => {
    const url = new URL(e.request.url);
    if (e.request.method !== 'GET' || url.origin !== self.location.origin) return;

    // Live data and private pages — never cached
    if (url.pathname.startsWith('/api/') || url.pathname.startsWith('/admin')) return;

    if (e.request.mode === 'navigate') {
        // Pages are cached by path; the query string only carries page state
        const key = new Request(url.pathname);
        e.respondWith(OFFLINE_PAGES.includes(url.pathname)
            ? staleWhileRevalidate(e, key, true)
            : networkFirst(key));
        return;
    }

    // Generated data: answer from cache at once, refresh in the background
    if (url.pathname.startsWith('/data/')) {
        e.respondWith(staleWhileRevalidate(e, e.request));
        return;
    }

    e.respondWith(cacheFirst(e.request));
});

async function staleWhileRevalidate(e, request, isPage = false) {
    const cache = await caches.open(CACHE);
    const cached = await cache.match(request, { ignoreSearch: true });
    const network = fetch(request).then(res => {
        if (res.ok) cache.put(request, res.clone());
        return res;
    });
    if (cached) {
        e.waitUntil(network.catch(() => {}));
        return cached;
    }
    return network.catch(() => isPage ? offlinePage() : Response.error());
}

async function networkFirst(request) {
    const cache = await caches.open(CACHE);
    try {
        const res = await fetch(request);
        if (res.ok) cache.put(request, res.clone());
        return res;
    } catch {
        return (await cache.match(request)) ?? offlinePage();
    }
}

// Static files. Their URLs don't change between versions, but the whole cache
// is replaced when the version changes, so nothing stale survives a deploy.
async function cacheFirst(request) {
    const cache = await caches.open(CACHE);
    const cached = await cache.match(request, { ignoreSearch: true });
    if (cached) return cached;
    const res = await fetch(request);
    if (res.ok) cache.put(request, res.clone());
    return res;
}

async function offlinePage() {
    return (await caches.match('/offline')) ?? Response.error();
}
