// Service worker for /admin/ only (generated by server/admin/index.js). Keeps
// the editor usable offline on the device you log in from; edits made offline
// are queued by the page itself and sent once the connection is back.
const CACHE = 'move-admin-{{version}}';
const PRECACHE = {{precache}};
// Give up on a bad connection quickly and use the cached copy
const NETWORK_TIMEOUT_MS = 4000;

self.addEventListener('install', e => {
    e.waitUntil(caches.open(CACHE).then(cache => cache.addAll(PRECACHE)));
    self.skipWaiting();
});

self.addEventListener('activate', e => {
    e.waitUntil(
        caches.keys().then(keys =>
            Promise.all(keys.filter(k => k.startsWith('move-admin-') && k !== CACHE).map(k => caches.delete(k)))
        )
    );
    self.clients.claim();
});

self.addEventListener('fetch', e => {
    const url = new URL(e.request.url);
    if (e.request.method !== 'GET' || url.origin !== self.location.origin) return;
    // Login, the export download and diagnostics always need the server (an old
    // diagnostics result shown from the cache would be misleading)
    if (['/admin/login', '/admin/api/export', '/admin/api/diagnostics'].includes(url.pathname)) return;

    e.respondWith(networkFirst(e.request, url));
});

async function networkFirst(request, url) {
    const cache = await caches.open(CACHE);
    const key = request.mode === 'navigate' ? new Request(url.pathname) : request;
    try {
        const res = await fetch(request, { signal: AbortSignal.timeout(NETWORK_TIMEOUT_MS) });
        // Don't cache redirects to the login page
        if (res.ok && !res.redirected) cache.put(key, res.clone());
        return res;
    } catch {
        return (await cache.match(key, { ignoreSearch: true })) ?? Response.error();
    }
}
